### ISSUE TITLE
RecyclerView item layout

### ISSUE THREAD

**Issue by LinusMuema** [kayere/cocktails#1]
Hey...
You could do away with [this layout](https://github.com/kayere/cocktails/blob/94bcb83201fdb20d49e8ec2581891aa91ed9f190/app/src/main/res/layout/drink_item.xml#L3) and have the cardview as the only view. This will make your recyclerview item cleaner.

**Comment by kayere** [comment]
Good catch @linusmuema. I did not notice that😂

**Comment by kayere** [comment]
Hey @LinusMuema, I have checked the issue. It wont work since the parent view needs to be a layout. I'll just replace constraint layout with frame layout since it holds one view.

**Comment by LinusMuema** [comment]
But it works on my machine 😂
Let me check something
